# Generated by Django 2.0.6 on 2018-06-18 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('telefone', models.CharField(max_length=11)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='chamados.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=128)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
                'verbose_name': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='StatusChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to='chamados.Funcionario'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.StatusChamado'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to='chamados.Funcionario'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.Chamado'),
        ),
    ]
