# Generated by Django 2.0.5 on 2018-06-18 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_auto_20180618_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 18, 20, 40, 0, 872363)),
        ),
    ]
