# Generated by Django 2.0.5 on 2018-06-18 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20180618_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 18, 20, 42, 35, 53572)),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
