# Generated by Django 2.0.5 on 2018-06-18 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_auto_20180618_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 20, 55, 22, 206666)),
        ),
    ]
